{% set name = "arrow-c-glib" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: 2dd8f0ea0848a58785628ee3a57675548d509e17213a2f5d72b0d900b43f5430

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('arrow-c-glib', max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - gobject-introspection
    - meson
    - ninja
    - pkg-config  # [osx]
  host:
    - arrow-cpp {{ version }}
    - glib
    - gobject-introspection
  run:
    - glib

test:
  commands:
    # headers
    - test -f $PREFIX/include/arrow-glib/arrow-glib.h  # [unix]
    - test -f $PREFIX/include/arrow-dataset-glib/arrow-dataset-glib.h  # [unix]
    - test -f $PREFIX/include/arrow-flight-glib/arrow-flight-glib.h  # [unix]
    - test -f $PREFIX/include/arrow-flight-sql-glib/arrow-flight-sql-glib.h  # [unix]
    - test -f $PREFIX/include/gandiva-glib/gandiva-glib.h  # [unix]
    - test -f $PREFIX/include/parquet-glib/parquet-glib.h  # [unix]
    - test -f $PREFIX/include/plasma-glib/plasma-glib.h  # [unix]
    # deps
    - test -f $PREFIX/include/glib-2.0/glib-object.h  # [unix]
    - test -f $PREFIX/lib/glib-2.0/include/glibconfig.h  # [unix]

    # shared
    - test -f $PREFIX/lib/libarrow-glib.so  # [linux]
    - test -f $PREFIX/lib/libarrow-dataset-glib.so  # [linux]
    - test -f $PREFIX/lib/libarrow-flight-glib.so  # [linux]
    - test -f $PREFIX/lib/libarrow-flight-sql-glib.so  # [linux]
    - test -f $PREFIX/lib/libgandiva-glib.so  # [linux]
    - test -f $PREFIX/lib/libparquet-glib.so  # [linux]
    - test -f $PREFIX/lib/libplasma-glib.so  # [linux]
    - test -f $PREFIX/lib/libarrow-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow-dataset-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow-flight-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libarrow-flight-sql-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libgandiva-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libparquet-glib.dylib  # [osx]
    - test -f $PREFIX/lib/libplasma-glib.dylib  # [osx]

    # Typelib
    - test -f $PREFIX/lib/girepository-1.0/Arrow-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/ArrowDataset-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/ArrowFlight-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/ArrowFlightSQL-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/Gandiva-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/Parquet-*.typelib  # [unix]
    - test -f $PREFIX/lib/girepository-1.0/Plasma-*.typelib  # [unix]

about:
  home: https://arrow.apache.org
  summary: Arrow GLib is a wrapper library for Arrow C++. Arrow GLib provides C API.
  description: |
    Apache Arrow is a development platform for in-memory analytics.
    It contains a set of technologies that enable big data systems
    to process and move data fast. Arrow GLib is a wrapper library for Arrow C++.
    Arrow GLib provides C API.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://arrow.apache.org/docs/
  dev_url: https://github.com/apache/arrow/tree/master

extra:
  recipe-maintainers:
    - xmnlab
    - xhochy
